// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: lifecycle.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LifecycleChaincode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sequence     int64  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Version      string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	InitRequired bool   `protobuf:"varint,4,opt,name=init_required,json=initRequired,proto3" json:"init_required,omitempty"`
}

func (x *LifecycleChaincode) Reset() {
	*x = LifecycleChaincode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifecycle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleChaincode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleChaincode) ProtoMessage() {}

func (x *LifecycleChaincode) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleChaincode.ProtoReflect.Descriptor instead.
func (*LifecycleChaincode) Descriptor() ([]byte, []int) {
	return file_lifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *LifecycleChaincode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LifecycleChaincode) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *LifecycleChaincode) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LifecycleChaincode) GetInitRequired() bool {
	if x != nil {
		return x.InitRequired
	}
	return false
}

type LifecycleStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelName string `protobuf:"bytes,1,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
}

func (x *LifecycleStatusRequest) Reset() {
	*x = LifecycleStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifecycle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleStatusRequest) ProtoMessage() {}

func (x *LifecycleStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleStatusRequest.ProtoReflect.Descriptor instead.
func (*LifecycleStatusRequest) Descriptor() ([]byte, []int) {
	return file_lifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *LifecycleStatusRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

type LifecycleStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chaincodes []*LifecycleChaincode `protobuf:"bytes,1,rep,name=chaincodes,proto3" json:"chaincodes,omitempty"`
}

func (x *LifecycleStatusResponse) Reset() {
	*x = LifecycleStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifecycle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleStatusResponse) ProtoMessage() {}

func (x *LifecycleStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleStatusResponse.ProtoReflect.Descriptor instead.
func (*LifecycleStatusResponse) Descriptor() ([]byte, []int) {
	return file_lifecycle_proto_rawDescGZIP(), []int{2}
}

func (x *LifecycleStatusResponse) GetChaincodes() []*LifecycleChaincode {
	if x != nil {
		return x.Chaincodes
	}
	return nil
}

type LifecycleFullRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelName    string   `protobuf:"bytes,1,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	ChaincodeName  string   `protobuf:"bytes,2,opt,name=chaincode_name,json=chaincodeName,proto3" json:"chaincode_name,omitempty"`
	ChaincodeLabel string   `protobuf:"bytes,3,opt,name=chaincode_label,json=chaincodeLabel,proto3" json:"chaincode_label,omitempty"`
	Policy         string   `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	Version        string   `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	InitArgs       []string `protobuf:"bytes,6,rep,name=init_args,json=initArgs,proto3" json:"init_args,omitempty"`
	InitRequired   bool     `protobuf:"varint,7,opt,name=init_required,json=initRequired,proto3" json:"init_required,omitempty"`
	CommitForce    bool     `protobuf:"varint,8,opt,name=commit_force,json=commitForce,proto3" json:"commit_force,omitempty"`
}

func (x *LifecycleFullRequest) Reset() {
	*x = LifecycleFullRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifecycle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleFullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleFullRequest) ProtoMessage() {}

func (x *LifecycleFullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleFullRequest.ProtoReflect.Descriptor instead.
func (*LifecycleFullRequest) Descriptor() ([]byte, []int) {
	return file_lifecycle_proto_rawDescGZIP(), []int{3}
}

func (x *LifecycleFullRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *LifecycleFullRequest) GetChaincodeName() string {
	if x != nil {
		return x.ChaincodeName
	}
	return ""
}

func (x *LifecycleFullRequest) GetChaincodeLabel() string {
	if x != nil {
		return x.ChaincodeLabel
	}
	return ""
}

func (x *LifecycleFullRequest) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *LifecycleFullRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LifecycleFullRequest) GetInitArgs() []string {
	if x != nil {
		return x.InitArgs
	}
	return nil
}

func (x *LifecycleFullRequest) GetInitRequired() bool {
	if x != nil {
		return x.InitRequired
	}
	return false
}

func (x *LifecycleFullRequest) GetCommitForce() bool {
	if x != nil {
		return x.CommitForce
	}
	return false
}

type LifecycleFullResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Committed bool            `protobuf:"varint,1,opt,name=committed,proto3" json:"committed,omitempty"`
	Approvals map[string]bool `protobuf:"bytes,2,rep,name=approvals,proto3" json:"approvals,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *LifecycleFullResponse) Reset() {
	*x = LifecycleFullResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifecycle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleFullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleFullResponse) ProtoMessage() {}

func (x *LifecycleFullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleFullResponse.ProtoReflect.Descriptor instead.
func (*LifecycleFullResponse) Descriptor() ([]byte, []int) {
	return file_lifecycle_proto_rawDescGZIP(), []int{4}
}

func (x *LifecycleFullResponse) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

func (x *LifecycleFullResponse) GetApprovals() map[string]bool {
	if x != nil {
		return x.Approvals
	}
	return nil
}

type LifecycleApprovedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelName   string `protobuf:"bytes,1,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	ChaincodeName string `protobuf:"bytes,2,opt,name=chaincode_name,json=chaincodeName,proto3" json:"chaincode_name,omitempty"`
}

func (x *LifecycleApprovedRequest) Reset() {
	*x = LifecycleApprovedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifecycle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleApprovedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleApprovedRequest) ProtoMessage() {}

func (x *LifecycleApprovedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleApprovedRequest.ProtoReflect.Descriptor instead.
func (*LifecycleApprovedRequest) Descriptor() ([]byte, []int) {
	return file_lifecycle_proto_rawDescGZIP(), []int{5}
}

func (x *LifecycleApprovedRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *LifecycleApprovedRequest) GetChaincodeName() string {
	if x != nil {
		return x.ChaincodeName
	}
	return ""
}

type LifecycleApprovedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chaincode *LifecycleChaincode `protobuf:"bytes,1,opt,name=chaincode,proto3" json:"chaincode,omitempty"`
	PackageId string              `protobuf:"bytes,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
}

func (x *LifecycleApprovedResponse) Reset() {
	*x = LifecycleApprovedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifecycle_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleApprovedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleApprovedResponse) ProtoMessage() {}

func (x *LifecycleApprovedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleApprovedResponse.ProtoReflect.Descriptor instead.
func (*LifecycleApprovedResponse) Descriptor() ([]byte, []int) {
	return file_lifecycle_proto_rawDescGZIP(), []int{6}
}

func (x *LifecycleApprovedResponse) GetChaincode() *LifecycleChaincode {
	if x != nil {
		return x.Chaincode
	}
	return nil
}

func (x *LifecycleApprovedResponse) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

type LifecycleCheckCommitReadinessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sequence      int64  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ChannelName   string `protobuf:"bytes,2,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	ChaincodeName string `protobuf:"bytes,3,opt,name=chaincode_name,json=chaincodeName,proto3" json:"chaincode_name,omitempty"`
	Policy        string `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	Version       string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	InitRequired  bool   `protobuf:"varint,6,opt,name=init_required,json=initRequired,proto3" json:"init_required,omitempty"`
}

func (x *LifecycleCheckCommitReadinessRequest) Reset() {
	*x = LifecycleCheckCommitReadinessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifecycle_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleCheckCommitReadinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleCheckCommitReadinessRequest) ProtoMessage() {}

func (x *LifecycleCheckCommitReadinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleCheckCommitReadinessRequest.ProtoReflect.Descriptor instead.
func (*LifecycleCheckCommitReadinessRequest) Descriptor() ([]byte, []int) {
	return file_lifecycle_proto_rawDescGZIP(), []int{7}
}

func (x *LifecycleCheckCommitReadinessRequest) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *LifecycleCheckCommitReadinessRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *LifecycleCheckCommitReadinessRequest) GetChaincodeName() string {
	if x != nil {
		return x.ChaincodeName
	}
	return ""
}

func (x *LifecycleCheckCommitReadinessRequest) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *LifecycleCheckCommitReadinessRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LifecycleCheckCommitReadinessRequest) GetInitRequired() bool {
	if x != nil {
		return x.InitRequired
	}
	return false
}

type LifecycleCheckCommitReadinessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Approvals map[string]bool `protobuf:"bytes,2,rep,name=approvals,proto3" json:"approvals,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *LifecycleCheckCommitReadinessResponse) Reset() {
	*x = LifecycleCheckCommitReadinessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifecycle_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleCheckCommitReadinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleCheckCommitReadinessResponse) ProtoMessage() {}

func (x *LifecycleCheckCommitReadinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleCheckCommitReadinessResponse.ProtoReflect.Descriptor instead.
func (*LifecycleCheckCommitReadinessResponse) Descriptor() ([]byte, []int) {
	return file_lifecycle_proto_rawDescGZIP(), []int{8}
}

func (x *LifecycleCheckCommitReadinessResponse) GetApprovals() map[string]bool {
	if x != nil {
		return x.Approvals
	}
	return nil
}

type LifecycleApproveForMyOrgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sequence       int64  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ChannelName    string `protobuf:"bytes,2,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	ChaincodeName  string `protobuf:"bytes,3,opt,name=chaincode_name,json=chaincodeName,proto3" json:"chaincode_name,omitempty"`
	ChaincodeLabel string `protobuf:"bytes,4,opt,name=chaincode_label,json=chaincodeLabel,proto3" json:"chaincode_label,omitempty"`
	Policy         string `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`
	Version        string `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	InitRequired   bool   `protobuf:"varint,7,opt,name=init_required,json=initRequired,proto3" json:"init_required,omitempty"`
}

func (x *LifecycleApproveForMyOrgRequest) Reset() {
	*x = LifecycleApproveForMyOrgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifecycle_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleApproveForMyOrgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleApproveForMyOrgRequest) ProtoMessage() {}

func (x *LifecycleApproveForMyOrgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleApproveForMyOrgRequest.ProtoReflect.Descriptor instead.
func (*LifecycleApproveForMyOrgRequest) Descriptor() ([]byte, []int) {
	return file_lifecycle_proto_rawDescGZIP(), []int{9}
}

func (x *LifecycleApproveForMyOrgRequest) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *LifecycleApproveForMyOrgRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *LifecycleApproveForMyOrgRequest) GetChaincodeName() string {
	if x != nil {
		return x.ChaincodeName
	}
	return ""
}

func (x *LifecycleApproveForMyOrgRequest) GetChaincodeLabel() string {
	if x != nil {
		return x.ChaincodeLabel
	}
	return ""
}

func (x *LifecycleApproveForMyOrgRequest) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *LifecycleApproveForMyOrgRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LifecycleApproveForMyOrgRequest) GetInitRequired() bool {
	if x != nil {
		return x.InitRequired
	}
	return false
}

type LifecycleCommitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sequence      int64  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ChannelName   string `protobuf:"bytes,2,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	ChaincodeName string `protobuf:"bytes,3,opt,name=chaincode_name,json=chaincodeName,proto3" json:"chaincode_name,omitempty"`
	Policy        string `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	Version       string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	InitRequired  bool   `protobuf:"varint,6,opt,name=init_required,json=initRequired,proto3" json:"init_required,omitempty"`
}

func (x *LifecycleCommitRequest) Reset() {
	*x = LifecycleCommitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifecycle_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleCommitRequest) ProtoMessage() {}

func (x *LifecycleCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleCommitRequest.ProtoReflect.Descriptor instead.
func (*LifecycleCommitRequest) Descriptor() ([]byte, []int) {
	return file_lifecycle_proto_rawDescGZIP(), []int{10}
}

func (x *LifecycleCommitRequest) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *LifecycleCommitRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *LifecycleCommitRequest) GetChaincodeName() string {
	if x != nil {
		return x.ChaincodeName
	}
	return ""
}

func (x *LifecycleCommitRequest) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *LifecycleCommitRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LifecycleCommitRequest) GetInitRequired() bool {
	if x != nil {
		return x.InitRequired
	}
	return false
}

type LifecycleInitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelName   string   `protobuf:"bytes,1,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	ChaincodeName string   `protobuf:"bytes,2,opt,name=chaincode_name,json=chaincodeName,proto3" json:"chaincode_name,omitempty"`
	InitArgs      []string `protobuf:"bytes,3,rep,name=init_args,json=initArgs,proto3" json:"init_args,omitempty"`
}

func (x *LifecycleInitRequest) Reset() {
	*x = LifecycleInitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lifecycle_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LifecycleInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleInitRequest) ProtoMessage() {}

func (x *LifecycleInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lifecycle_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleInitRequest.ProtoReflect.Descriptor instead.
func (*LifecycleInitRequest) Descriptor() ([]byte, []int) {
	return file_lifecycle_proto_rawDescGZIP(), []int{11}
}

func (x *LifecycleInitRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *LifecycleInitRequest) GetChaincodeName() string {
	if x != nil {
		return x.ChaincodeName
	}
	return ""
}

func (x *LifecycleInitRequest) GetInitArgs() []string {
	if x != nil {
		return x.InitArgs
	}
	return nil
}

var File_lifecycle_proto protoreflect.FileDescriptor

var file_lifecycle_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x01, 0x0a, 0x12, 0x4c, 0x69, 0x66,
	0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x69,
	0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0c, 0x69, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x3b,
	0x0a, 0x16, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x54, 0x0a, 0x17, 0x4c,
	0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63,
	0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65,
	0x73, 0x22, 0xa0, 0x02, 0x0a, 0x14, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x46,
	0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a,
	0x0e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64,
	0x65, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x61, 0x72, 0x67, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x69, 0x74, 0x41, 0x72, 0x67, 0x73, 0x12, 0x23, 0x0a, 0x0d,
	0x69, 0x6e, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x63,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x46,
	0x6f, 0x72, 0x63, 0x65, 0x22, 0xbe, 0x01, 0x0a, 0x15, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63,
	0x6c, 0x65, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x12, 0x49, 0x0a, 0x09,
	0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c,
	0x65, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x70,
	0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x61, 0x70,
	0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x73, 0x1a, 0x3c, 0x0a, 0x0e, 0x41, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x61, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x64, 0x0a, 0x18, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63,
	0x6c, 0x65, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x73, 0x0a, 0x19, 0x4c,
	0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x22, 0xe3, 0x01, 0x0a, 0x24, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x6e, 0x69, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0xc0, 0x01, 0x0a, 0x25, 0x4c, 0x69, 0x66, 0x65, 0x63,
	0x79, 0x63, 0x6c, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52,
	0x65, 0x61, 0x64, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x59, 0x0a, 0x09, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x3b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x66, 0x65,
	0x63, 0x79, 0x63, 0x6c, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x09, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x73, 0x1a, 0x3c, 0x0a, 0x0e, 0x41,
	0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x87, 0x02, 0x0a, 0x1f, 0x4c, 0x69,
	0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x46, 0x6f,
	0x72, 0x4d, 0x79, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65,
	0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23,
	0x0a, 0x0d, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x64, 0x22, 0xd5, 0x01, 0x0a, 0x16, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a,
	0x0e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69,
	0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x7d, 0x0a, 0x14, 0x4c,
	0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63,
	0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x69, 0x6e, 0x69, 0x74, 0x41, 0x72, 0x67, 0x73, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69,
	0x74, 0x6c, 0x61, 0x62, 0x2e, 0x6e, 0x2d, 0x74, 0x2e, 0x69, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2f, 0x68, 0x6c, 0x66, 0x2d, 0x74, 0x6f, 0x6f,
	0x6c, 0x2f, 0x68, 0x6c, 0x66, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2d, 0x70, 0x6c,
	0x61, 0x6e, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_lifecycle_proto_rawDescOnce sync.Once
	file_lifecycle_proto_rawDescData = file_lifecycle_proto_rawDesc
)

func file_lifecycle_proto_rawDescGZIP() []byte {
	file_lifecycle_proto_rawDescOnce.Do(func() {
		file_lifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(file_lifecycle_proto_rawDescData)
	})
	return file_lifecycle_proto_rawDescData
}

var file_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_lifecycle_proto_goTypes = []interface{}{
	(*LifecycleChaincode)(nil),                    // 0: proto.LifecycleChaincode
	(*LifecycleStatusRequest)(nil),                // 1: proto.LifecycleStatusRequest
	(*LifecycleStatusResponse)(nil),               // 2: proto.LifecycleStatusResponse
	(*LifecycleFullRequest)(nil),                  // 3: proto.LifecycleFullRequest
	(*LifecycleFullResponse)(nil),                 // 4: proto.LifecycleFullResponse
	(*LifecycleApprovedRequest)(nil),              // 5: proto.LifecycleApprovedRequest
	(*LifecycleApprovedResponse)(nil),             // 6: proto.LifecycleApprovedResponse
	(*LifecycleCheckCommitReadinessRequest)(nil),  // 7: proto.LifecycleCheckCommitReadinessRequest
	(*LifecycleCheckCommitReadinessResponse)(nil), // 8: proto.LifecycleCheckCommitReadinessResponse
	(*LifecycleApproveForMyOrgRequest)(nil),       // 9: proto.LifecycleApproveForMyOrgRequest
	(*LifecycleCommitRequest)(nil),                // 10: proto.LifecycleCommitRequest
	(*LifecycleInitRequest)(nil),                  // 11: proto.LifecycleInitRequest
	nil,                                           // 12: proto.LifecycleFullResponse.ApprovalsEntry
	nil,                                           // 13: proto.LifecycleCheckCommitReadinessResponse.ApprovalsEntry
}
var file_lifecycle_proto_depIdxs = []int32{
	0,  // 0: proto.LifecycleStatusResponse.chaincodes:type_name -> proto.LifecycleChaincode
	12, // 1: proto.LifecycleFullResponse.approvals:type_name -> proto.LifecycleFullResponse.ApprovalsEntry
	0,  // 2: proto.LifecycleApprovedResponse.chaincode:type_name -> proto.LifecycleChaincode
	13, // 3: proto.LifecycleCheckCommitReadinessResponse.approvals:type_name -> proto.LifecycleCheckCommitReadinessResponse.ApprovalsEntry
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_lifecycle_proto_init() }
func file_lifecycle_proto_init() {
	if File_lifecycle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lifecycle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleChaincode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lifecycle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lifecycle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lifecycle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleFullRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lifecycle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleFullResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lifecycle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleApprovedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lifecycle_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleApprovedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lifecycle_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleCheckCommitReadinessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lifecycle_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleCheckCommitReadinessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lifecycle_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleApproveForMyOrgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lifecycle_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleCommitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lifecycle_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LifecycleInitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lifecycle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lifecycle_proto_goTypes,
		DependencyIndexes: file_lifecycle_proto_depIdxs,
		MessageInfos:      file_lifecycle_proto_msgTypes,
	}.Build()
	File_lifecycle_proto = out.File
	file_lifecycle_proto_rawDesc = nil
	file_lifecycle_proto_goTypes = nil
	file_lifecycle_proto_depIdxs = nil
}
